# Introduction to Tensorflow in DeepLearning for indepth understanding

1. **[TensorFlow](https://en.wikipedia.org/wiki/TensorFlow)** is an open-source framework developed by Google for numerical computation, machine learning, and deep learning.

2. Its fundamental data structure is the **[Tensor](https://en.wikipedia.org/wiki/Tensor_(machine_learning))**, which represents data as scalars, vectors, matrices, or multidimensional arrays.

3. TensorFlow provides mathematical operations such as **addition, multiplication, matrix multiplication, reshaping, and reduction** on tensors.

4. It supports automatic differentiation to calculate **[gradients](https://en.wikipedia.org/wiki/Gradient)**, which are essential for training neural networks through **[backpropagation](https://en.wikipedia.org/wiki/Backpropagation)**.

5. It provides building blocks such as **layers, activation functions, loss functions, and optimizers** for constructing **[neural networks](https://en.wikipedia.org/wiki/Neural_network_(machine_learning))**.

6. **[Keras](https://en.wikipedia.org/wiki/Keras)** is a high-level API that makes building and training neural networks simpler.

7. TensorFlow can execute computations on **CPU, GPU, and other accelerators**, making it suitable for large-scale deep-learning workloads.

8. A typical deep-learning workflow is: **Dataset → Tensor → Neural Network → Loss → Gradient → Weight Update → Trained Model**.

9. Therefore, TensorFlow is not just a library for tensors—it provides the **computational foundation for building, training, evaluating, and deploying deep-learning models**.

In [ ]:
# In colab notebook, tensorflow is pre-installed in the virtual machine.
# We can directly import the library.
# In other environments, tensorflow should be installed beforehand using command `pip install tensorflow`
import tensorflow as tf

In [ ]:
# dir(tf) is used to list all the attributes, functions,
# classes, and modules available inside the TensorFlow library.
# This is a generic python method and can be used on any python object
dir(tf)

['AggregationMethod',
 'Assert',
 'CriticalSection',
 'DType',
 'DeviceSpec',
 'GradientTape',
 'Graph',
 'IndexedSlices',
 'IndexedSlicesSpec',
 'Module',
 'Operation',
 'OptionalSpec',
 'RaggedTensor',
 'RaggedTensorSpec',
 'RegisterGradient',
 'SparseTensor',
 'SparseTensorSpec',
 'Tensor',
 'TensorArray',
 'TensorArraySpec',
 'TensorShape',
 'TensorSpec',
 'TypeSpec',
 'UnconnectedGradients',
 'Variable',
 'VariableAggregation',
 'VariableSynchronization',
 '_API_MODULE',
 '_KerasLazyLoader',
 '__all__',
 '__builtins__',
 '__cached__',
 '__compiler_version__',
 '__cxx11_abi_flag__',
 '__cxx_version__',
 '__doc__',
 '__file__',
 '__git_version__',
 '__internal__',
 '__loader__',
 '__monolithic_build__',
 '__name__',
 '__operators__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_api',
 '_compat',
 '_current_file_location',
 '_current_module',
 '_fi',
 '_initializers',
 '_inspect',
 '_kernel_dir',
 '_ll',
 '_losses',
 '_major_api_version',
 '_metrics',
 '_module_dir',


In [ ]:
print(tf.__version__)

2.20.0


In [ ]:
# Create a 2D tensor
tensor = tf.constant([
    ["10", "20", "30"],
    ["40", "50", "60"]
])

print("Tensor:")
print(tensor)

print("Shape:", tensor.shape)
print("Number of dimensions:", len(tensor.shape))
print("Data type:", tensor.dtype)

# Access an element
print("Element at row 1, column 2:", tensor[1, 2])

Tensor:
tf.Tensor(
[[b'10' b'20' b'30']
 [b'40' b'50' b'60']], shape=(2, 3), dtype=string)
Shape: (2, 3)
Number of dimensions: 2
Data type: <dtype: 'string'>
Element at row 1, column 2: tf.Tensor(b'60', shape=(), dtype=string)


In [ ]:
tensor = tf.constant([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])

print("Tensor:")
print(tensor)

print("Shape:", tensor.shape)
print("Dimensions:", len(tensor.shape))

# Access one element
print("Element:", tensor[1, 0, 2])

Tensor:
tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
Shape: (2, 2, 3)
Dimensions: 3
Element: tf.Tensor(9, shape=(), dtype=int32)


In [ ]:
tensor = tf.constant([
    [
        [[1, 2], [3, 4]],
        [[5, 6], [7, 8]]
    ],
    [
        [[9, 10], [11, 12]],
        [[13, 14], [15, 16]]
    ]
])

print("Tensor:")
print(tensor)

print("Shape:", tensor.shape)
print("Dimensions:", len(tensor.shape))

# Access one element
print("Element:", tensor[1, 0, 1, 0])

Tensor:
tf.Tensor(
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]], shape=(2, 2, 2, 2), dtype=int32)
Shape: (2, 2, 2, 2)
Dimensions: 4
Element: tf.Tensor(11, shape=(), dtype=int32)


In [ ]:
import tensorflow as tf

# Create a tensor
a = tf.constant([[1, 2, 3],
                 [4, 5, 6]])

print("Tensor:")
print(a)

# 1. Addition
print("\nAddition:")
print(a + 10)



Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Addition:
tf.Tensor(
[[11 12 13]
 [14 15 16]], shape=(2, 3), dtype=int32)


In [ ]:
# 2. Multiplication
print("\nMultiplication:")
print(a * 2)




Multiplication:
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
# 3. Element-wise addition
b = tf.constant([[10, 20, 30],
                 [40, 50, 60]])

print("\nElement-wise addition:")
print(a + b)




Element-wise addition:
tf.Tensor(
[[11 22 33]
 [44 55 66]], shape=(2, 3), dtype=int32)


In [ ]:
# 4. Element-wise multiplication
print("\nElement-wise multiplication:")
print(a * b)




Element-wise multiplication:
tf.Tensor(
[[ 10  40  90]
 [160 250 360]], shape=(2, 3), dtype=int32)


In [ ]:
# 5. Shape
print("\nShape:")
print(a.shape)




Shape:
(2, 3)


In [ ]:
# 6. Indexing
print("\nFirst row:")
print(a[0])

print("\nElement at row 2, column 3:")
print(a[1, 2])




First row:
tf.Tensor([1 2 3], shape=(3,), dtype=int32)

Element at row 2, column 3:
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
# 7. Reshape
print("\nReshape:")
print(tf.reshape(a, (3, 2)))





Reshape:
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
# 8. Sum
print("\nSum:")
print(tf.reduce_sum(a))




Sum:
tf.Tensor(21, shape=(), dtype=int32)


In [ ]:
# 9. Mean
print("\nMean:")
print(tf.reduce_mean(a))




Mean:
tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
# 10. Maximum
print("\nMaximum:")
print(tf.reduce_max(a))


Maximum:
tf.Tensor(6, shape=(), dtype=int32)


In [ ]:
# MORE OPERATIONS Creation — constant(), zeros(), ones(), fill()
# Shape — shape, rank, size
# Indexing & slicing — tensor[0], tensor[:, 1]
# Arithmetic — +, -, *, /
# Matrix operations — matmul(), transpose()
# Reshaping — reshape(), expand_dims(), squeeze()
# Aggregation — reduce_sum(), reduce_mean(), reduce_max(), reduce_min()
# Comparison — equal(), greater(), less()
# Concatenation — concat(), stack()
# Splitting — split(), unstack()
# Mathematical — sqrt(), exp(), log(), square()
# Random tensors — random.normal(), random.uniform()
# Type conversion — cast()
# Linear algebra — linalg.inv(), linalg.det(), etc.
# Neural-network operations — activations, convolution, pooling, etc.

In [ ]:
# | #  | Operation         | Example                |
# | -- | ----------------- | ---------------------- |
# | 1  | `tf.constant()`   | `tf.constant([1,2,3])` |
# | 2  | `tf.zeros()`      | `tf.zeros((2,3))`      |
# | 3  | `tf.ones()`       | `tf.ones((2,3))`       |
# | 4  | `tf.fill()`       | `tf.fill((2,3), 5)`    |
# | 5  | `tf.zeros_like()` | `tf.zeros_like(x)`     |
# | 6  | `tf.ones_like()`  | `tf.ones_like(x)`      |
# | 7  | `tf.range()`      | `tf.range(0,10)`       |
# | 8  | `tf.linspace()`   | `tf.linspace(0.,1.,5)` |
# | 9  | `tf.eye()`        | `tf.eye(3)`            |
# | 10 | `tf.identity()`   | `tf.identity(x)`       |


In [ ]:
# | #  | Operation    | Example       |
# | -- | ------------ | ------------- |
# | 11 | `tf.shape()` | `tf.shape(x)` |
# | 12 | `tf.rank()`  | `tf.rank(x)`  |
# | 13 | `tf.size()`  | `tf.size(x)`  |
# | 14 | `.shape`     | `x.shape`     |
# | 15 | `.dtype`     | `x.dtype`     |
# | 16 | `.ndim`      | `x.ndim`      |


In [ ]:
# | #  | Operation           | Example                    |
# | -- | ------------------- | -------------------------- |
# | 17 | Indexing            | `x[0]`                     |
# | 18 | Multi-indexing      | `x[1,2]`                   |
# | 19 | Slicing             | `x[:,1]`                   |
# | 20 | `tf.gather()`       | `tf.gather(x,[0,2])`       |
# | 21 | `tf.gather_nd()`    | `tf.gather_nd(x, [[0,1]])` |
# | 22 | `tf.boolean_mask()` | `tf.boolean_mask(x, mask)` |


In [ ]:
# | #  | Operation       | Example            |
# | -- | --------------- | ------------------ |
# | 23 | Addition        | `x + y`            |
# | 24 | Subtraction     | `x - y`            |
# | 25 | Multiplication  | `x * y`            |
# | 26 | Division        | `x / y`            |
# | 27 | `tf.add()`      | `tf.add(x,y)`      |
# | 28 | `tf.subtract()` | `tf.subtract(x,y)` |
# | 29 | `tf.multiply()` | `tf.multiply(x,y)` |
# | 30 | `tf.divide()`   | `tf.divide(x,y)`   |
# | 31 | `tf.pow()`      | `tf.pow(x,2)`      |
# | 32 | `tf.mod()`      | `tf.math.mod(x,2)` |


In [ ]:
# | #  | Operation         | Example            |
# | -- | ----------------- | ------------------ |
# | 33 | `tf.abs()`        | `tf.abs(x)`        |
# | 34 | `tf.square()`     | `tf.square(x)`     |
# | 35 | `tf.sqrt()`       | `tf.sqrt(x)`       |
# | 36 | `tf.exp()`        | `tf.exp(x)`        |
# | 37 | `tf.math.log()`   | `tf.math.log(x)`   |
# | 38 | `tf.math.log1p()` | `tf.math.log1p(x)` |
# | 39 | `tf.math.ceil()`  | `tf.math.ceil(x)`  |
# | 40 | `tf.math.floor()` | `tf.math.floor(x)` |
# | 41 | `tf.math.round()` | `tf.math.round(x)` |
# | 42 | `tf.math.sign()`  | `tf.math.sign(x)`  |


In [ ]:
# | #  | Operation              | Example                      |
# | -- | ---------------------- | ---------------------------- |
# | 43 | `tf.reduce_sum()`      | `tf.reduce_sum(x)`           |
# | 44 | `tf.reduce_mean()`     | `tf.reduce_mean(x)`          |
# | 45 | `tf.reduce_max()`      | `tf.reduce_max(x)`           |
# | 46 | `tf.reduce_min()`      | `tf.reduce_min(x)`           |
# | 47 | `tf.reduce_prod()`     | `tf.reduce_prod(x)`          |
# | 48 | `tf.reduce_std()`      | `tf.math.reduce_std(x)`      |
# | 49 | `tf.reduce_variance()` | `tf.math.reduce_variance(x)` |
# | 50 | `tf.argmax()`          | `tf.argmax(x)`               |
# | 51 | `tf.argmin()`          | `tf.argmin(x)`               |


In [ ]:
# | #  | Operation            | Example                 |
# | -- | -------------------- | ----------------------- |
# | 52 | `tf.equal()`         | `tf.equal(x,y)`         |
# | 53 | `tf.not_equal()`     | `tf.not_equal(x,y)`     |
# | 54 | `tf.greater()`       | `tf.greater(x,y)`       |
# | 55 | `tf.greater_equal()` | `tf.greater_equal(x,y)` |
# | 56 | `tf.less()`          | `tf.less(x,y)`          |
# | 57 | `tf.less_equal()`    | `tf.less_equal(x,y)`    |
# | 58 | `tf.maximum()`       | `tf.maximum(x,y)`       |
# | 59 | `tf.minimum()`       | `tf.minimum(x,y)`       |


In [ ]:
# | #  | Operation           | Example                    |
# | -- | ------------------- | -------------------------- |
# | 60 | `tf.reshape()`      | `tf.reshape(x,(3,2))`      |
# | 61 | `tf.transpose()`    | `tf.transpose(x)`          |
# | 62 | `tf.expand_dims()`  | `tf.expand_dims(x,0)`      |
# | 63 | `tf.squeeze()`      | `tf.squeeze(x)`            |
# | 64 | `tf.broadcast_to()` | `tf.broadcast_to(x,(2,3))` |
# | 65 | `tf.ensure_shape()` | `tf.ensure_shape(x,(2,3))` |


In [ ]:
# | #  | Operation      | Example                   |
# | -- | -------------- | ------------------------- |
# | 66 | `tf.concat()`  | `tf.concat([x,y],axis=0)` |
# | 67 | `tf.stack()`   | `tf.stack([x,y])`         |
# | 68 | `tf.unstack()` | `tf.unstack(x)`           |
# | 69 | `tf.split()`   | `tf.split(x,2)`           |
# | 70 | `tf.tile()`    | `tf.tile(x,[2,1])`        |
# | 71 | `tf.repeat()`  | `tf.repeat(x,2)`          |
# | 72 | `tf.pad()`     | `tf.pad(x,[[1,1],[1,1]])` |


In [ ]:
# | #  | Operation            | Example                 |
# | -- | -------------------- | ----------------------- |
# | 73 | `tf.matmul()`        | `tf.matmul(A,B)`        |
# | 74 | `tf.linalg.matvec()` | `tf.linalg.matvec(A,x)` |
# | 75 | `tf.linalg.diag()`   | `tf.linalg.diag(x)`     |
# | 76 | `tf.linalg.det()`    | `tf.linalg.det(A)`      |
# | 77 | `tf.linalg.inv()`    | `tf.linalg.inv(A)`      |
# | 78 | `tf.linalg.norm()`   | `tf.linalg.norm(x)`     |
# | 79 | `tf.linalg.solve()`  | `tf.linalg.solve(A,b)`  |
# | 80 | `tf.linalg.svd()`    | `tf.linalg.svd(A)`      |


In [ ]:
# | #  | Operation                      | Example                             |
# | -- | ------------------------------ | ----------------------------------- |
# | 81 | `tf.random.uniform()`          | `tf.random.uniform((2,3))`          |
# | 82 | `tf.random.normal()`           | `tf.random.normal((2,3))`           |
# | 83 | `tf.random.truncated_normal()` | `tf.random.truncated_normal((2,3))` |
# | 84 | `tf.random.shuffle()`          | `tf.random.shuffle(x)`              |
# | 85 | `tf.random.set_seed()`         | `tf.random.set_seed(42)`            |


In [ ]:
# | #  | Operation                | Example                      |
# | -- | ------------------------ | ---------------------------- |
# | 86 | `tf.cast()`              | `tf.cast(x,tf.float32)`      |
# | 87 | `tf.convert_to_tensor()` | `tf.convert_to_tensor(data)` |
# | 88 | `tf.strings.to_number()` | `tf.strings.to_number(x)`    |


In [ ]:
# | #  | Operation          | Example               |
# | -- | ------------------ | --------------------- |
# | 89 | `tf.logical_and()` | `tf.logical_and(a,b)` |
# | 90 | `tf.logical_or()`  | `tf.logical_or(a,b)`  |
# | 91 | `tf.logical_not()` | `tf.logical_not(a)`   |
# | 92 | `tf.where()`       | `tf.where(x>0,x,0)`   |
# | 93 | `tf.math.is_nan()` | `tf.math.is_nan(x)`   |
# | 94 | `tf.math.is_inf()` | `tf.math.is_inf(x)`   |


In [ ]:
# | #   | Operation   | Example                 |
# | --- | ----------- | ----------------------- |
# | 95  | ReLU        | `tf.nn.relu(x)`         |
# | 96  | Sigmoid     | `tf.nn.sigmoid(x)`      |
# | 97  | Softmax     | `tf.nn.softmax(x)`      |
# | 98  | Dropout     | `tf.nn.dropout(x,0.2)`  |
# | 99  | Convolution | `tf.nn.conv2d(...)`     |
# | 100 | Max Pooling | `tf.nn.max_pool2d(...)` |


## TensorFlow Operations — Learning Levels

### Level 1 — Must Know

- `constant`
- `shape`
- `indexing`
- `arithmetic`
- `reshape`
- `sum`
- `mean`
- `max`
- `min`
- `concat`

These operations form the **basic foundation for working with tensors**.

---

### Level 2 — ML/DL Essential

- `matmul`
- `transpose`
- `random`
- `cast`
- `argmax`
- `softmax`
- `ReLU`
- `sigmoid`
- `convolution`
- `pooling`

These operations are commonly used when working with **Machine Learning and Deep Learning models**.

---

### Level 3 — Reference

The remaining TensorFlow operations can be **learned as and when a project requires them**.

---

### Key Concept

> **TensorFlow provides operations to create, inspect, transform, calculate with, and learn from tensors.**